package com.artland.entity;

import java.io.Serializable;
import java.util.Date;

public class Comment implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.blog_id
     *
     * @mbg.generated
     */
    private Long blogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.media_id
     *
     * @mbg.generated
     */
    private Long mediaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.commentator
     *
     * @mbg.generated
     */
    private String commentator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.website_url
     *
     * @mbg.generated
     */
    private String websiteUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.comment_body
     *
     * @mbg.generated
     */
    private String commentBody;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.comment_create_time
     *
     * @mbg.generated
     */
    private Date commentCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.commentator_ip
     *
     * @mbg.generated
     */
    private String commentatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.reply_body
     *
     * @mbg.generated
     */
    private String replyBody;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.reply_create_time
     *
     * @mbg.generated
     */
    private Date replyCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.comment_status
     *
     * @mbg.generated
     */
    private Byte commentStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.is_deleted
     *
     * @mbg.generated
     */
    private Byte isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_comment
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment
     *
     * @mbg.generated
     */
    public Comment(Long id, Long blogId, Long mediaId, String commentator, String email, String websiteUrl, String commentBody, Date commentCreateTime, String commentatorIp, String replyBody, Date replyCreateTime, Byte commentStatus, Byte isDeleted, Integer userId) {
        this.id = id;
        this.blogId = blogId;
        this.mediaId = mediaId;
        this.commentator = commentator;
        this.email = email;
        this.websiteUrl = websiteUrl;
        this.commentBody = commentBody;
        this.commentCreateTime = commentCreateTime;
        this.commentatorIp = commentatorIp;
        this.replyBody = replyBody;
        this.replyCreateTime = replyCreateTime;
        this.commentStatus = commentStatus;
        this.isDeleted = isDeleted;
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment
     *
     * @mbg.generated
     */
    public Comment() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.id
     *
     * @return the value of tb_comment.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.id
     *
     * @param id the value for tb_comment.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.blog_id
     *
     * @return the value of tb_comment.blog_id
     *
     * @mbg.generated
     */
    public Long getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.blog_id
     *
     * @param blogId the value for tb_comment.blog_id
     *
     * @mbg.generated
     */
    public void setBlogId(Long blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.media_id
     *
     * @return the value of tb_comment.media_id
     *
     * @mbg.generated
     */
    public Long getMediaId() {
        return mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.media_id
     *
     * @param mediaId the value for tb_comment.media_id
     *
     * @mbg.generated
     */
    public void setMediaId(Long mediaId) {
        this.mediaId = mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.commentator
     *
     * @return the value of tb_comment.commentator
     *
     * @mbg.generated
     */
    public String getCommentator() {
        return commentator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.commentator
     *
     * @param commentator the value for tb_comment.commentator
     *
     * @mbg.generated
     */
    public void setCommentator(String commentator) {
        this.commentator = commentator == null ? null : commentator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.email
     *
     * @return the value of tb_comment.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.email
     *
     * @param email the value for tb_comment.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.website_url
     *
     * @return the value of tb_comment.website_url
     *
     * @mbg.generated
     */
    public String getWebsiteUrl() {
        return websiteUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.website_url
     *
     * @param websiteUrl the value for tb_comment.website_url
     *
     * @mbg.generated
     */
    public void setWebsiteUrl(String websiteUrl) {
        this.websiteUrl = websiteUrl == null ? null : websiteUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.comment_body
     *
     * @return the value of tb_comment.comment_body
     *
     * @mbg.generated
     */
    public String getCommentBody() {
        return commentBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.comment_body
     *
     * @param commentBody the value for tb_comment.comment_body
     *
     * @mbg.generated
     */
    public void setCommentBody(String commentBody) {
        this.commentBody = commentBody == null ? null : commentBody.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.comment_create_time
     *
     * @return the value of tb_comment.comment_create_time
     *
     * @mbg.generated
     */
    public Date getCommentCreateTime() {
        return commentCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.comment_create_time
     *
     * @param commentCreateTime the value for tb_comment.comment_create_time
     *
     * @mbg.generated
     */
    public void setCommentCreateTime(Date commentCreateTime) {
        this.commentCreateTime = commentCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.commentator_ip
     *
     * @return the value of tb_comment.commentator_ip
     *
     * @mbg.generated
     */
    public String getCommentatorIp() {
        return commentatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.commentator_ip
     *
     * @param commentatorIp the value for tb_comment.commentator_ip
     *
     * @mbg.generated
     */
    public void setCommentatorIp(String commentatorIp) {
        this.commentatorIp = commentatorIp == null ? null : commentatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.reply_body
     *
     * @return the value of tb_comment.reply_body
     *
     * @mbg.generated
     */
    public String getReplyBody() {
        return replyBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.reply_body
     *
     * @param replyBody the value for tb_comment.reply_body
     *
     * @mbg.generated
     */
    public void setReplyBody(String replyBody) {
        this.replyBody = replyBody == null ? null : replyBody.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.reply_create_time
     *
     * @return the value of tb_comment.reply_create_time
     *
     * @mbg.generated
     */
    public Date getReplyCreateTime() {
        return replyCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.reply_create_time
     *
     * @param replyCreateTime the value for tb_comment.reply_create_time
     *
     * @mbg.generated
     */
    public void setReplyCreateTime(Date replyCreateTime) {
        this.replyCreateTime = replyCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.comment_status
     *
     * @return the value of tb_comment.comment_status
     *
     * @mbg.generated
     */
    public Byte getCommentStatus() {
        return commentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.comment_status
     *
     * @param commentStatus the value for tb_comment.comment_status
     *
     * @mbg.generated
     */
    public void setCommentStatus(Byte commentStatus) {
        this.commentStatus = commentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.is_deleted
     *
     * @return the value of tb_comment.is_deleted
     *
     * @mbg.generated
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.is_deleted
     *
     * @param isDeleted the value for tb_comment.is_deleted
     *
     * @mbg.generated
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.user_id
     *
     * @return the value of tb_comment.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.user_id
     *
     * @param userId the value for tb_comment.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", blogId=").append(blogId);
        sb.append(", mediaId=").append(mediaId);
        sb.append(", commentator=").append(commentator);
        sb.append(", email=").append(email);
        sb.append(", websiteUrl=").append(websiteUrl);
        sb.append(", commentBody=").append(commentBody);
        sb.append(", commentCreateTime=").append(commentCreateTime);
        sb.append(", commentatorIp=").append(commentatorIp);
        sb.append(", replyBody=").append(replyBody);
        sb.append(", replyCreateTime=").append(replyCreateTime);
        sb.append(", commentStatus=").append(commentStatus);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", userId=").append(userId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}