package com.artland.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Media implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_media.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_media.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_media.sub_url
     *
     * @mbg.generated
     */
    private String subUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_media.cover_image
     *
     * @mbg.generated
     */
    private String coverImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_media.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_media.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_media.dimension
     *
     * @mbg.generated
     */
    private String dimension;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_media.resolution
     *
     * @mbg.generated
     */
    private String resolution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_media.format
     *
     * @mbg.generated
     */
    private String format;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_media.duration
     *
     * @mbg.generated
     */
    private String duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_media.size
     *
     * @mbg.generated
     */
    private String size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_media.license
     *
     * @mbg.generated
     */
    private String license;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_media.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_media.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_media.purchases
     *
     * @mbg.generated
     */
    private Long purchases;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_media.views
     *
     * @mbg.generated
     */
    private Long views;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_media.downloads
     *
     * @mbg.generated
     */
    private Long downloads;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_media.category_id
     *
     * @mbg.generated
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_media.category_name
     *
     * @mbg.generated
     */
    private String categoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_media.tags
     *
     * @mbg.generated
     */
    private String tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_media.enable_comment
     *
     * @mbg.generated
     */
    private Byte enableComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_media.is_deleted
     *
     * @mbg.generated
     */
    private Byte isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_media.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_media.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_media.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_media
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_media
     *
     * @mbg.generated
     */
    public Media(Long id, String title, String subUrl, String coverImage, String description, String content, String dimension, String resolution, String format, String duration, String size, String license, Byte status, BigDecimal price, Long purchases, Long views, Long downloads, Integer categoryId, String categoryName, String tags, Byte enableComment, Byte isDeleted, Date createTime, Date updateTime, Integer userId) {
        this.id = id;
        this.title = title;
        this.subUrl = subUrl;
        this.coverImage = coverImage;
        this.description = description;
        this.content = content;
        this.dimension = dimension;
        this.resolution = resolution;
        this.format = format;
        this.duration = duration;
        this.size = size;
        this.license = license;
        this.status = status;
        this.price = price;
        this.purchases = purchases;
        this.views = views;
        this.downloads = downloads;
        this.categoryId = categoryId;
        this.categoryName = categoryName;
        this.tags = tags;
        this.enableComment = enableComment;
        this.isDeleted = isDeleted;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_media
     *
     * @mbg.generated
     */
    public Media() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_media.id
     *
     * @return the value of tb_media.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_media.id
     *
     * @param id the value for tb_media.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_media.title
     *
     * @return the value of tb_media.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_media.title
     *
     * @param title the value for tb_media.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_media.sub_url
     *
     * @return the value of tb_media.sub_url
     *
     * @mbg.generated
     */
    public String getSubUrl() {
        return subUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_media.sub_url
     *
     * @param subUrl the value for tb_media.sub_url
     *
     * @mbg.generated
     */
    public void setSubUrl(String subUrl) {
        this.subUrl = subUrl == null ? null : subUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_media.cover_image
     *
     * @return the value of tb_media.cover_image
     *
     * @mbg.generated
     */
    public String getCoverImage() {
        return coverImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_media.cover_image
     *
     * @param coverImage the value for tb_media.cover_image
     *
     * @mbg.generated
     */
    public void setCoverImage(String coverImage) {
        this.coverImage = coverImage == null ? null : coverImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_media.description
     *
     * @return the value of tb_media.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_media.description
     *
     * @param description the value for tb_media.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_media.content
     *
     * @return the value of tb_media.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_media.content
     *
     * @param content the value for tb_media.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_media.dimension
     *
     * @return the value of tb_media.dimension
     *
     * @mbg.generated
     */
    public String getDimension() {
        return dimension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_media.dimension
     *
     * @param dimension the value for tb_media.dimension
     *
     * @mbg.generated
     */
    public void setDimension(String dimension) {
        this.dimension = dimension == null ? null : dimension.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_media.resolution
     *
     * @return the value of tb_media.resolution
     *
     * @mbg.generated
     */
    public String getResolution() {
        return resolution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_media.resolution
     *
     * @param resolution the value for tb_media.resolution
     *
     * @mbg.generated
     */
    public void setResolution(String resolution) {
        this.resolution = resolution == null ? null : resolution.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_media.format
     *
     * @return the value of tb_media.format
     *
     * @mbg.generated
     */
    public String getFormat() {
        return format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_media.format
     *
     * @param format the value for tb_media.format
     *
     * @mbg.generated
     */
    public void setFormat(String format) {
        this.format = format == null ? null : format.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_media.duration
     *
     * @return the value of tb_media.duration
     *
     * @mbg.generated
     */
    public String getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_media.duration
     *
     * @param duration the value for tb_media.duration
     *
     * @mbg.generated
     */
    public void setDuration(String duration) {
        this.duration = duration == null ? null : duration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_media.size
     *
     * @return the value of tb_media.size
     *
     * @mbg.generated
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_media.size
     *
     * @param size the value for tb_media.size
     *
     * @mbg.generated
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_media.license
     *
     * @return the value of tb_media.license
     *
     * @mbg.generated
     */
    public String getLicense() {
        return license;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_media.license
     *
     * @param license the value for tb_media.license
     *
     * @mbg.generated
     */
    public void setLicense(String license) {
        this.license = license == null ? null : license.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_media.status
     *
     * @return the value of tb_media.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_media.status
     *
     * @param status the value for tb_media.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_media.price
     *
     * @return the value of tb_media.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_media.price
     *
     * @param price the value for tb_media.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_media.purchases
     *
     * @return the value of tb_media.purchases
     *
     * @mbg.generated
     */
    public Long getPurchases() {
        return purchases;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_media.purchases
     *
     * @param purchases the value for tb_media.purchases
     *
     * @mbg.generated
     */
    public void setPurchases(Long purchases) {
        this.purchases = purchases;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_media.views
     *
     * @return the value of tb_media.views
     *
     * @mbg.generated
     */
    public Long getViews() {
        return views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_media.views
     *
     * @param views the value for tb_media.views
     *
     * @mbg.generated
     */
    public void setViews(Long views) {
        this.views = views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_media.downloads
     *
     * @return the value of tb_media.downloads
     *
     * @mbg.generated
     */
    public Long getDownloads() {
        return downloads;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_media.downloads
     *
     * @param downloads the value for tb_media.downloads
     *
     * @mbg.generated
     */
    public void setDownloads(Long downloads) {
        this.downloads = downloads;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_media.category_id
     *
     * @return the value of tb_media.category_id
     *
     * @mbg.generated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_media.category_id
     *
     * @param categoryId the value for tb_media.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_media.category_name
     *
     * @return the value of tb_media.category_name
     *
     * @mbg.generated
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_media.category_name
     *
     * @param categoryName the value for tb_media.category_name
     *
     * @mbg.generated
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_media.tags
     *
     * @return the value of tb_media.tags
     *
     * @mbg.generated
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_media.tags
     *
     * @param tags the value for tb_media.tags
     *
     * @mbg.generated
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_media.enable_comment
     *
     * @return the value of tb_media.enable_comment
     *
     * @mbg.generated
     */
    public Byte getEnableComment() {
        return enableComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_media.enable_comment
     *
     * @param enableComment the value for tb_media.enable_comment
     *
     * @mbg.generated
     */
    public void setEnableComment(Byte enableComment) {
        this.enableComment = enableComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_media.is_deleted
     *
     * @return the value of tb_media.is_deleted
     *
     * @mbg.generated
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_media.is_deleted
     *
     * @param isDeleted the value for tb_media.is_deleted
     *
     * @mbg.generated
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_media.create_time
     *
     * @return the value of tb_media.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_media.create_time
     *
     * @param createTime the value for tb_media.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_media.update_time
     *
     * @return the value of tb_media.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_media.update_time
     *
     * @param updateTime the value for tb_media.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_media.user_id
     *
     * @return the value of tb_media.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_media.user_id
     *
     * @param userId the value for tb_media.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_media
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", subUrl=").append(subUrl);
        sb.append(", coverImage=").append(coverImage);
        sb.append(", description=").append(description);
        sb.append(", content=").append(content);
        sb.append(", dimension=").append(dimension);
        sb.append(", resolution=").append(resolution);
        sb.append(", format=").append(format);
        sb.append(", duration=").append(duration);
        sb.append(", size=").append(size);
        sb.append(", license=").append(license);
        sb.append(", status=").append(status);
        sb.append(", price=").append(price);
        sb.append(", purchases=").append(purchases);
        sb.append(", views=").append(views);
        sb.append(", downloads=").append(downloads);
        sb.append(", categoryId=").append(categoryId);
        sb.append(", categoryName=").append(categoryName);
        sb.append(", tags=").append(tags);
        sb.append(", enableComment=").append(enableComment);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", userId=").append(userId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}