package com.artland.dao;

import com.artland.entity.Media;
import com.artland.entity.MediaExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface MediaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_media
     *
     * @mbg.generated
     */
    long countByExample(MediaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_media
     *
     * @mbg.generated
     */
    int deleteByExample(MediaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_media
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_media
     *
     * @mbg.generated
     */
    int insert(Media record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_media
     *
     * @mbg.generated
     */
    int insertSelective(Media record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_media
     *
     * @mbg.generated
     */
    List<Media> selectByExampleWithRowbounds(MediaExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_media
     *
     * @mbg.generated
     */
    List<Media> selectByExample(MediaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_media
     *
     * @mbg.generated
     */
    Media selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_media
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Media record, @Param("example") MediaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_media
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Media record, @Param("example") MediaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_media
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Media record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_media
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Media record);
}