package com.artland.dao;

import com.artland.entity.TagRelation;
import com.artland.entity.TagRelationExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface TagRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tag_relation
     *
     * @mbg.generated
     */
    long countByExample(TagRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tag_relation
     *
     * @mbg.generated
     */
    int deleteByExample(TagRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tag_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tag_relation
     *
     * @mbg.generated
     */
    int insert(TagRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tag_relation
     *
     * @mbg.generated
     */
    int insertSelective(TagRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tag_relation
     *
     * @mbg.generated
     */
    List<TagRelation> selectByExampleWithRowbounds(TagRelationExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tag_relation
     *
     * @mbg.generated
     */
    List<TagRelation> selectByExample(TagRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tag_relation
     *
     * @mbg.generated
     */
    TagRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tag_relation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TagRelation record, @Param("example") TagRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tag_relation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TagRelation record, @Param("example") TagRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tag_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TagRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tag_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TagRelation record);

    /**
     * 根据多个Id查询关系表
     * @param ids
     * @return
     */
    List<Integer> selectDistinctTagsByIds(Integer[] ids);

}